sudo: required

services:
  - docker

language: c

before_install:
  - gem install ghi

script:
  - env
  - asdfi

after_failure:
  - FAILED="$?" && [ "$TRAVIS_PULL_REQUEST" != "false" ] && ghi comment -m "failed. [$FAILED]" $TRAVIS_PULL_REQUEST
