language: c

compiler:
  - gcc

os:
- linux

env:
  - MAKEFLAGS='-j2'

addons:
  apt:
    sources:
      kalakris-cmake
    packages:
      - cmake
      - systemtap-sdt-dev
      - libelf-dev

script:
  - mkdir build && cd build && cmake .. && make
