sudo: required

services:
  - docker

language: c

compiler:
  - gcc

os:
- linux

script:
  - mkdir ../CUBRID
  - docker run --name build -v`pwd`/../cubrid:/home/cubrid -v`pwd`/../CUBRID:/home/CUBRID -e MAKEFLAGS='-j 2' cubridci/build
  - ls
  - ls -al CUBRID
