language: c

compiler:
  - gcc

os:
- linux

addons:
  apt:
    sources:
      kalakris-cmake
    packages:
      - cmake
      - systemtap-sdt-dev
      - libelf-dev

script:
  - mkdir build && cd build && cmake .. && make

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: version.h
  skip_cleanup: true
  on:
    tags: true
