sudo: required

services:
  - docker

language: c

before_install:
  - gem install ghi

script:
  - env
  - asdfa

after_failure:
  - FAILED="$?" && [ "$TRAVIS_FULL_REQUEST" != "false" ] && ghi comment -m "failed. [$FAILED]" $TRAVIS_FULL_REQUEST
