sudo: required

services:
  - docker

language: c

before_install:
  - gem install ghi

script:
  - env
  - asdfi
  - FAILED=$?

after_failure:
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ghi comment -m "failed. [$FAILED]" $TRAVIS_PULL_REQUEST; fi
