defaults: &defaults
  working_directory: /home
  docker:
    - image: cubridci/cubridci

test_defaults: &test_defaults
  steps:
    - attach_workspace:
        at: .
    - run:
        name: Test
        shell: /bin/bash
        command: /entrypoint.sh test
    - store_test_results:
        path: /tmp/tests

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      MAKEFLAGS: -j2
    
    steps:
      - checkout:
          path: cubrid
      - run:
          name: Build
          command: /entrypoint.sh build
      - persist_to_workspace:
          root: .
          paths:
            - CUBRID

  test_medium:
    <<: *defaults
    environment:
      TEST_SUITE: medium
    <<: *test_defaults

  test_sql:
    <<: *defaults
    environment:
      TEST_SUITE: sql
    <<: *test_defaults

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test_medium:
          requires:
            - build
      - test_sql:
          requires:
            - build
