defaults: &defaults
  working_directory: /home
  docker:
    - image: cubridci/cubridci

version: 2
jobs:
  build:
    <<: *defaults
    environment:
      MAKEFLAGS: -j2
    
    steps:
      - checkout:
          path: cubrid
      - run: /entrypoint.sh build
      - persist_to_workspace:
          root: .
          paths:
            - CUBRID

  test_medium:
    <<: *defaults
    environment:
      TEST_SUITE: medium

    steps:
      - attach_workspace:
          at: CUBRID
      - run: env && ls
      - run: /entrypoint.sh test

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test_medium:
          requires:
            - build
